apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: test01
spec:
  reclaimable: true
  weight: 1
  capability:
    cpu: "4"
    memory: "4096Mi"
    nvidia.com/t4: 40
status:
  state: Open